app = "ds2024-g16"
primary_region = "arn"

[build]
builder = "paketobuildpacks/builder:base"

[env]
PORT = "8080"
SIGNALING_SERVER_PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
size = "shared-cpu-1x"
cpu_kind = "shared"
cpus = 1
memory = "256mb"
